version: '3.4'

services:
    postgres:
        container_name: pg
        image: postgres:10.5
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=eventstoredemo
        ports:
            - '5432:5432'
        volumes:
            - ./docker-volumes/postgres-data:/var/lib/postgresql/data
    eventstore:
        container_name: es
        image: ghcr.io/eventstore/eventstore:21.10.0-alpha-arm64v8
        environment:
            - EVENTSTORE_CLUSTER_SIZE=1
            - EVENTSTORE_RUN_PROJECTIONS=All
            - EVENTSTORE_START_STANDARD_PROJECTIONS=true
            - EVENTSTORE_EXT_TCP_PORT=1113
            - EVENTSTORE_HTTP_PORT=2113
            - EVENTSTORE_INSECURE=true
            - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
            - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
            - EVENTSTORE_MEM_DB=false
        ports:
            - '1113:1113'
            - '2113:2113'
        volumes:
            - ./docker-volumes/eventstore-volume-data:/var/lib/eventstore
            - ./docker-volumes/eventstore-volume-logs:/var/log/eventstore