version: "3.4"

services:
  eventstore.db:
    image: ghcr.io/eventstore/eventstore:21.10.0-alpha-arm64v8
    environment:
      - EVENTSTORE_CLUSTER_SIZE=${EVENTSTORE_CLUSTER_SIZE}
      - EVENTSTORE_RUN_PROJECTIONS=${EVENTSTORE_RUN_PROJECTIONS}
      - EVENTSTORE_START_STANDARD_PROJECTIONS=${EVENTSTORE_START_STANDARD_PROJECTIONS}
      - EVENTSTORE_EXT_TCP_PORT=${EVENTSTORE_EXT_TCP_PORT}
      - EVENTSTORE_HTTP_PORT=${EVENTSTORE_HTTP_PORT}
      - EVENTSTORE_INSECURE=${EVENTSTORE_INSECURE}
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=${EVENTSTORE_ENABLE_EXTERNAL_TCP}
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=${EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP}
      - EVENTSTORE_CLUSTER_GOSSIP_PORT=${EVENTSTORE_CLUSTER_GOSSIP_PORT}
      - EVENTSTORE_GOSSIP_ON_SINGLE_NODE=${EVENTSTORE_GOSSIP_ON_SINGLE_NODE}
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
